version: '3.7'

services:
  app:
    build: .
    container_name: symfony_app
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    networks:
      - my-network

networks:
  my-network:
